import { Json } from './json';
let details_arr = [
    'Bundl Technologies Private Limited(Swiggy)',
    'Hector Beverages Private Limited',
    'Puma Sports India Private Limited',
    'Dewan Housing Finance Corporation Ltd',
    'Infosys Limited',
    'Think & Learn Private Limited',
    'Delhivery Private Limited',
    'Wow Momo Foods Private Limited',
    'Rebel Foods Private Limited(Faasos)',
    'Lendingkart Technologies Private Limited',
    'ID Fresh Food(India) Private Limited',
    'Bharathiasha Technologies Private Limited (PrivateCircle)',
    'Gala Precision Engineering Private Limited',
    'Balaji Wafers Private Limited',
    'Sangeetha Mobiles Private Limited',
    'Vodafone Idea limited',
    'Vakrangee Ltd.',
    'Bundl Technologies Private Limited(Swiggy)',
    'Hector Beverages Private Limited',
    'Puma Sports India Private Limited',
    'Dewan Housing Finance Corporation Ltd',
    'Infosys Limited',
    'Think & Learn Private Limited',
    'Delhivery Private Limited',
    'Wow Momo Foods Private Limited',
    'Rebel Foods Private Limited(Faasos)',
    'Lendingkart Technologies Private Limited',
    'ID Fresh Food(India) Private Limited',
    'Bharathiasha Technologies Private Limited (PrivateCircle)',
    'Gala Precision Engineering Private Limited',
    'Balaji Wafers Private Limited',
    'Sangeetha Mobiles Private Limited',
    'Vodafone Idea limited',
    'Vakrangee Ltd.'
]
export const DETAILS: Json[] = [
    { date: "", list_name: "Competitive Intelligence", no_of_entities: 0, details: [], selected: false, id: 1 },
    { date: "", list_name: "My Vendors", no_of_entities: 0, details: [], selected: false, id: 2 },
    { date: "", list_name: "My Customers", no_of_entities: 0, details: [], selected: false, id: 3 },
    { date: "Jul 23", list_name: "Test_30_results", no_of_entities: 28, details: details_arr, selected: false, id: 4 },
    { date: "Jul 28", list_name: "To_index", no_of_entities: 100, details: details_arr, selected: false, id: 5 },
    { date: "Apr 10", list_name: "KPMG Requested Companies-Listed Set_Prasada Kumar", no_of_entities: 34, details: details_arr, selected: false, id: 6 },
    { date: "Mar 12", list_name: "Error Case- LTB To EBITDA Blank_Prasada Kumar ", no_of_entities: 24, details: details_arr, selected: false, id: 7 },
    { date: "Dec 14", list_name: "Two Companies", no_of_entities: 2, details: details_arr, selected: false, id: 8 },
    { date: "Nov 01", list_name: "Custom", no_of_entities: 30, details: details_arr, selected: false, id: 9 },
    { date: "Oct 29", list_name: "Mumbai", no_of_entities: 3, details: details_arr, selected: false, id: 10 },
    { date: "", list_name: "Competitive Intellignece", no_of_entities: 0, details: [], selected: false, id: 11 },
    { date: "", list_name: "My Vendors", no_of_entities: 0, details: [], selected: false, id: 12 },
    { date: "", list_name: "My Customers", no_of_entities: 0, details: [], selected: false, id: 13 },
    { date: "Jul 23", list_name: "Test_30_results", no_of_entities: 28, details: details_arr, selected: false, id: 14 },
];